services:

  ellm:
    build: .
    container_name: ellm
    hostname: ellm
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    ports:
      - "${ELLM_PORT:-45100}:80"
    environment:
      DATA_DIR: /data
    volumes:
      - ./data:/data
      - ./src:/opt/ellm/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, compute, utility]
